import type { ExerciseAnimationConfig } from './types';

const CONFIGS: ExerciseAnimationConfig[] = [
  {
    exerciseId: 'ex-band-shrug',
    view: 'standing-front',
    animationClass: 'band-shrug',
    caption: 'Lift shoulders toward ears · 2s hold · slow lower',
    captionHe: 'הרמת כתפיים לעבר האוזניים · החזקה 2 שניות · הורדה איטית',
    durationMs: 3500,
  },
  {
    exerciseId: 'ex-levator-stretch',
    view: 'seated-side',
    animationClass: 'levator-stretch',
    caption: 'Look down-and-away · gentle hand assist · 30s hold',
    captionHe: 'הבטה מטה והצידה · סיוע עדין של היד · החזקה 30 שניות',
    durationMs: 4000,
  },
  {
    exerciseId: 'ex-chin-tuck-band',
    view: 'seated-side',
    animationClass: 'chin-tuck',
    caption: 'Slide chin straight back · pause · return',
    captionHe: 'הזזת סנטר ישר אחורה · השהיה · חזרה',
    durationMs: 3000,
  },
  {
    exerciseId: 'ex-band-external-rotation',
    view: 'standing-side',
    animationClass: 'ext-rotation',
    caption: 'Elbow at side · rotate forearm outward · control return',
    captionHe: 'מרפק צמוד לגוף · סיבוב אמה החוצה · חזרה מבוקרת',
    durationMs: 3000,
  },
  {
    exerciseId: 'ex-lateral-raise',
    view: 'standing-front',
    animationClass: 'lateral-raise',
    caption: 'Raise arms to shoulder height · pause · lower slowly',
    captionHe: 'הרמת זרועות עד גובה כתפיים · השהיה · הורדה איטית',
    durationMs: 3500,
  },
  {
    exerciseId: 'ex-face-pull',
    view: 'standing-front',
    animationClass: 'face-pull',
    caption: 'Pull band to forehead · elbows wide · squeeze shoulder blades',
    captionHe: 'משיכת הגומיה למצח · מרפקים פתוחים · כיווץ שכמות',
    durationMs: 3000,
  },
  {
    exerciseId: 'ex-banded-biceps-eccentric',
    view: 'standing-front',
    animationClass: 'biceps-curl',
    caption: 'Curl up fast · lower slowly (3s eccentric)',
    captionHe: 'כיווץ מהיר למעלה · הורדה איטית (3 שניות אקסצנטרי)',
    durationMs: 3500,
  },
  {
    exerciseId: 'ex-seated-row',
    view: 'seated-side',
    animationClass: 'seated-row',
    caption: 'Pull band to ribs · elbows back · squeeze · return',
    captionHe: 'משיכת הגומיה לצלעות · מרפקים אחורה · כיווץ · חזרה',
    durationMs: 3000,
  },
  {
    exerciseId: 'ex-ytw',
    view: 'standing-front',
    animationClass: 'ytw',
    caption: 'Y · then T · then W · squeeze shoulder blades each rep',
    captionHe: 'Y · ואז T · ואז W · כיווץ שכמות בכל חזרה',
    durationMs: 5000,
  },
  {
    exerciseId: 'ex-good-morning',
    view: 'standing-side',
    animationClass: 'good-morning',
    caption: 'Hinge at hips · flat back · return to upright',
    captionHe: 'כיפוף מפרק הירך · גב שטוח · חזרה זקופה',
    durationMs: 3500,
  },
  {
    exerciseId: 'ex-median-nerve-glide',
    view: 'hand-close-up',
    animationClass: 'nerve-glide',
    caption: 'Wrist extend + neck side-bend away · gentle, no pain',
    captionHe: 'יישור שורש כף יד + הטיית צוואר הצידה · עדין, בלי כאב',
    durationMs: 4000,
  },
  {
    exerciseId: 'ex-wrist-extension',
    view: 'arm-close-up',
    animationClass: 'wrist-ext',
    caption: 'Extend wrist against band · control return',
    captionHe: 'יישור שורש כף יד נגד הגומיה · חזרה מבוקרת',
    durationMs: 2800,
  },
  {
    exerciseId: 'ex-tyler-twist',
    view: 'arm-close-up',
    animationClass: 'tyler-twist',
    caption: 'Twist with strong hand · slow eccentric back',
    captionHe: 'סיבוב עם היד החזקה · חזרה אקסצנטרית איטית',
    durationMs: 3500,
  },
  {
    exerciseId: 'ex-reverse-tyler',
    view: 'arm-close-up',
    animationClass: 'reverse-tyler',
    caption: 'Reverse twist · slow controlled return',
    captionHe: 'סיבוב הפוך · חזרה איטית ומבוקרת',
    durationMs: 3500,
  },
  {
    exerciseId: 'ex-banded-thumb-eccentric',
    view: 'arm-close-up',
    animationClass: 'thumb-eccentric',
    caption: 'Thumb extends · slow eccentric back to neutral',
    captionHe: 'יישור אגודל · חזרה אקסצנטרית איטית לניטרלי',
    durationMs: 3200,
  },
  {
    exerciseId: 'ex-banded-clamshell',
    view: 'side-lying',
    animationClass: 'clamshell',
    caption: 'Knees together · open top knee · keep pelvis still',
    captionHe: 'ברכיים יחד · פתיחת הברך העליונה · אגן יציב',
    durationMs: 3000,
  },
  {
    exerciseId: 'ex-banded-glute-bridge',
    view: 'supine',
    animationClass: 'glute-bridge',
    caption: 'Press hips up · squeeze glutes · lower with control',
    captionHe: 'הרמת אגן · כיווץ עכוז · הורדה מבוקרת',
    durationMs: 3500,
  },
  {
    exerciseId: 'ex-banded-tke',
    view: 'leg-close-up',
    animationClass: 'tke',
    caption: 'Lock knee straight against band · slow release',
    captionHe: 'יישור הברך נגד הגומיה · שחרור איטי',
    durationMs: 2800,
  },
  {
    exerciseId: 'ex-banded-hamstring-curl',
    view: 'leg-close-up',
    animationClass: 'hamstring-curl',
    caption: 'Curl heel toward glute · slow eccentric return',
    captionHe: 'כיפוף עקב לעבר העכוז · חזרה אקסצנטרית איטית',
    durationMs: 3000,
  },
  {
    exerciseId: 'ex-eccentric-heel-drop',
    view: 'leg-close-up',
    animationClass: 'heel-drop',
    caption: 'Rise on toes · slow eccentric drop below step',
    captionHe: 'עלייה על קצות אצבעות · ירידה אקסצנטרית איטית מתחת למדרגה',
    durationMs: 4000,
  },
  {
    exerciseId: 'ex-plantar-fascia-stretch',
    view: 'leg-close-up',
    animationClass: 'plantar-stretch',
    caption: 'Pull toes back · feel arch stretch · 10s hold',
    captionHe: 'משיכת אצבעות לאחור · תחושת מתיחה בקשת · החזקה 10 שניות',
    durationMs: 4000,
  },
  {
    exerciseId: 'ex-banded-eversion',
    view: 'leg-close-up',
    animationClass: 'ankle-eversion',
    caption: 'Turn foot outward against band · control return',
    captionHe: 'סיבוב כף הרגל החוצה נגד הגומיה · חזרה מבוקרת',
    durationMs: 2600,
  },
];

export const ANIMATION_CONFIGS: Record<string, ExerciseAnimationConfig> = Object.fromEntries(
  CONFIGS.map((c) => [c.exerciseId, c]),
);
